# Generated by Django 4.0.4 on 2022-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='nacimiento',
            field=models.DateField(default='2000-11-28'),
            preserve_default=False,
        ),
    ]
